version: '3.7'

services:
 web:
  build:
   context: .
  ports:
  - "5000:5000"
  volumes:
  - ./:/rest-app

 mysqldb:
  image: mysql
  ports:
  - "3306:3306"
  environment:
  - MYSQL_ROOT_PASSWORD=p@ssw0rd
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:
